version: "3.8"
services:
  mongo-express:
    environment:
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=$ME_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$ME_BASICAUTH_PASSWORD
  express-be-main:
    build:
      target: prod
    environment:
      - NODE_ENV=prod
  react-fe-main:
    build:
      target: prod
      args:
        REACT_APP_EXPRESS_BE_MAIN_FQDN: $EXPRESS_BE_MAIN_FQDN
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - $REACT_FE_MAIN_LOCAL_PORT:80
    user: "0"